language: cpp
dist: xenial
sudo: false

compiler:
- clang
- gcc

services:
   - docker

addons:
  postgresql: "9.3"
  apt:
    sources:
    - llvm-toolchain-trusty-3.5
    - llvm-toolchain-trusty-5.0
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - bison
    - clang-3.5
    - flex
    - g++-4.9
    - libpq-dev
    - libpq5
    - libstdc++6
    - libtool
    - pkg-config
    - clang-format-5.0
    - pandoc
    - libffi-dev
    - build-essential
    - docker-ce

before_install:
   -  

install:
   -  
before_script:
   - pip -V
   - pip install --user invoke
   - pip install --user pipenv

script: 
   - pipenv sync
   - pipenv run invoke start-core
   - docker ps

cache:
  directories:
  - $HOME/.ccache
  - .libs

branches:
 only:
 - master

