---

- name: pull docker image. this tends to fail on the first time.
  docker_service:
    project_src: /opt/horizon
    stopped: yes
    pull: yes
  ignore_errors: yes

- name: pull docker image - again.
  docker_service:
    project_src: /opt/horizon
    stopped: yes
    pull: yes

- name: start horizon
  docker_service:
    project_src: /opt/horizon
