---
- name: create stellar-core mount directory
  file:
    path: /opt/stellar-core/volumes/stellar-core
    state: directory
    mode: 0655

- name: template stellar-core.cfg
  template:
    src: stellar-core.cfg.j2
    dest: /opt/stellar-core/volumes/stellar-core/stellar-core.cfg
    mode: 0600

- name: template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/stellar-core/docker-compose.yml
    mode: 0644

- name: pull docker image - this tends to fail so ignore errors
  docker_service:
    project_src: /opt/stellar-core
    pull: yes
    stopped: yes
  ignore_errors: yes

- name: pull docker image - again
  docker_service:
    project_src: /opt/stellar-core
    pull: yes
    stopped: yes

- name: copy init_core script to remote
  copy:
    src: "{{ role_path }}/files/opt/stellar-core/init_core.sh"
    dest: /opt/stellar-core/init_core.sh
    mode: 0700

- name: initialize database
  command: docker-compose run --rm stellar-core --newdb
  args:
    chdir: /opt/stellar-core

- name: initialize scp
  command: docker-compose run --rm stellar-core --forcescp
  args:
    chdir: /opt/stellar-core

- name: initialize history archive
  command: docker-compose run --rm stellar-core --newhist my-bucket
  args:
    chdir: /opt/stellar-core

- name: start stellar-core
  docker_service:
    project_src: /opt/stellar-core
